{
 "title": "Suricata- Zeek-Node-exporter disk graphs",
 "description": "Prometheus + node-exporter dashboard for viewing disk performance, utilization and saturation.",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(node_time_seconds, instance)"
   },
   {
    "name": "CPU",
    "query": "label_values(node_cpu_seconds_total, cpu)"
   },
   {
    "name": "Disk",
    "query": "label_values(node_disk_write_time_seconds_total, device)"
   },
   { "name": "RateInterval", "query": "20s,1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Suricata-Log4shell",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/eve.json\"} |= `jndi:ldap://` | json"
    }
   ]
  },
  {
   "title": "Suricata",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/eve.json\"} | json | event_type = `alert` | __error__=`` | line_format `{{.alert_signature}}` | regexp `(?P<cve>CVE-[0-9]{4}-[0-9]{4,7})`"
    }
   ]
  },
  {
   "title": "Suricata – Top CVE Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (cve) (\n    count_over_time(\n      {filename=\"/var/log/eve.json\"} | json | event_type=\"alert\" | __error__=\"\"\n      | line_format \"{{.alert_signature}}\"\n      | regexp \"(?P<cve>CVE-[0-9]{4}-[0-9]{4,7})\"\n    [$__range])\n  )\n)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Suricata",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/eve.json\"} |= ``"
    }
   ]
  },
  {
   "title": "Suricata",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/eve.json\"} |= ``"
    }
   ]
  },
  {
   "title": "Suricata – CVE Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (cve) (\n    count_over_time(\n      {filename=\"/var/log/eve.json\"} | json | event_type=\"alert\" | __error__=\"\"\n      | line_format \"{{.alert_signature}}\"\n      | regexp \"(?P<cve>CVE-[0-9]{4}-[0-9]{4,7})\"\n    [$__range])\n  )\n)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Zeek",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{filename=~\"/zeek-logs/.*\\\\.log\"} |= ``"
    }
   ]
  },
  {
   "title": "zeek-Times-series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"/zeek-logs/.*\\\\.log\"} |~ \"http.log\" |~ \"%27|UNION|SELECT\" [1m]))"
    }
   ]
  },
  {
   "title": "zeek-Pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  count_over_time(\n    {filename=~\"/zeek-logs/.*\\\\.log\"} |~ \"http.log\" | pattern \"<_> <_> <_> <_> <method> <host> <uri> <referrer> <user_agent> <request_body_len> <response_body_len> <status_code> <_>\"\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=~\"$Node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory active {{ instance }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$Node\"}",
     "legendFormat": "Memory buffers {{ instance }}"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$Node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory cached {{ instance }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node\"}",
     "legendFormat": "Total memory {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory write cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{instance=~\"$Node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Dirty bytes {{ instance }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Writeback_bytes{instance=~\"$Node\"}",
     "legendFormat": "Writeback bytes {{ instance }}"
    }
   ]
  },
  {
   "title": "OOM killed procs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{instance=~\"$Node\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IO Wait per core",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=~\"$CPU\", instance=~\"$Node\", mode=\"iowait\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} CPU {{ cpu }}/{{ mode }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "min(rate(node_cpu_seconds_total{cpu=~\"$CPU\", instance=~\"$Node\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cpu=~\"$CPU\", instance=~\"$Node\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(rate(node_cpu_seconds_total{cpu=~\"$CPU\", instance=~\"$Node\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Disk active time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Weighted IO time {{ device }} {{ instance }}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Write time {{ device }} {{ instance }}"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Read time {{ device }} {{ instance }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": " rate(node_disk_written_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_writes_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": " rate(node_disk_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_reads_completed_total{instance=~\"$Node\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zeek",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "{filename=~\"/zeek-logs/.*\\\\.log\"} |= ``"
    }
   ]
  }
 ]
}